/*insertando datos para probar unions ejemplo*/

CREATE TABLE REGIONS1
(
 REGION_ID NUMBER PRIMARY KEY,
 REGION_NAME VARCHAR2(25)
 );
 
 INSERT INTO REGIONS1 VALUES (1,'Europe');
 INSERT INTO REGIONS1 VALUES (3,'Asia');
 INSERT INTO REGIONS1 VALUES (6,'Australia');
 INSERT INTO REGIONS1 VALUES (8,'Antartica');
 
 commit;
 
 
 
 SELECT REGION_ID,REGION_NAME FROM REGIONS
 UNION
 SELECT REGION_ID,REGION_NAME FROM REGIONS1;
 
SELECT REGION_ID,REGION_NAME FROM REGIONS
 UNION ALL
 SELECT REGION_ID,REGION_NAME FROM REGIONS1;
 
 SELECT REGION_ID,REGION_NAME FROM REGIONS
 INTERSECT
 SELECT REGION_ID,REGION_NAME FROM REGIONS1;
 
  SELECT REGION_ID,REGION_NAME FROM REGIONS
 MINUS
 SELECT REGION_ID,REGION_NAME FROM REGIONS1;
 
SELECT REGION_ID,REGION_NAME FROM REGIONS1
 MINUS
 SELECT REGION_ID,REGION_NAME FROM REGIONS;
 
 /*practica*/
 --CREAR LAS TABLAS
CREATE TABLE COCHES1
(
CODIGO NUMBER primary key,
NOMBRE VARCHAR2(100));
CREATE TABLE COCHES2
(
CODIGO NUMBER primary key,
NAME VARCHAR2(100));
--INSERTAR DATOS EN TABLAS
INSERT INTO COCHES1 VALUES(1,'BMW 3');
INSERT INTO COCHES1 VALUES(2,'AUDI A5');
INSERT INTO COCHES1 VALUES(3,'CITROEN C5');
INSERT INTO COCHES1 VALUES(4,'RENAULT CLIO');
INSERT INTO COCHES2 VALUES(1,'BMW 3');
INSERT INTO COCHES2 VALUES(6,'MERCEDES C');
INSERT INTO COCHES2 VALUES(3,'CITROEN C5');
INSERT INTO COCHES2 VALUES(7,'FORD MUSTANG');
COMMIT;

SELECT * FROM COCHES1
UNION  
SELECT * FROM COCHES2;

SELECT * FROM COCHES1
UNION ALL 
SELECT * FROM COCHES2;

SELECT * FROM COCHES1
INTERSECT  
SELECT * FROM COCHES2;

SELECT * FROM COCHES1
MINUS  
SELECT * FROM COCHES2;