INSERT INTO productos2 (code,name ) VALUES (1,'CLAVOS' );
commit;

DELETE FROM PRODUCTOS2 WHERE CODE=1;

ROLLBACK;

INSERT INTO productos2 ( code,name ) VALUES (2,'ARANDELAS' );
INSERT INTO productos2 ( code,name ) VALUES (3,'ESCARPIAS' );

SAVEPOINT A;
SELECT * FROM PRODUCTOS2;
UPDATE PRODUCTOS2 SET NAME='TORNILLOS' WHERE CODE=3;

ROLLBACK TO SAVEPOINT A;
COMMIT;