SELECT COUNT(*)FROM EMPLOYEES WHERE DEPARTMENT_ID=50;

SELECT COUNT(*)FROM EMPLOYEES WHERE HIRE_DATE LIKE '%/%/07';

SELECT MAX(SALARY)-MIN(SALARY) AS "DIFERENCIA ENTRE SALARIO MAYOR Y MENOR" FROM EMPLOYEES;

SELECT SUM(SALARY) AS "TOTAL SALARIOS" FROM EMPLOYEES WHERE DEPARTMENT_ID=100;

SELECT ROUND(AVG(SALARY),2), DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

SELECT COUNT(*) AS "NUMERO DE CIUDADES", COUNTRY_ID FROM LOCATIONS GROUP BY COUNTRY_ID;

SELECT ROUND(AVG(SALARY),2), DEPARTMENT_ID FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL GROUP BY DEPARTMENT_ID;

SELECT COUNT(*) AS "NUMERO DE EMPLEADOS",TO_CHAR(HIRE_DATE,'YYYY') AS "AÑO" FROM EMPLOYEES GROUP BY TO_CHAR(HIRE_DATE,'YYYY') HAVING COUNT(*)>10;

SELECT COUNT(*) AS "NUMERO DE EMPLEADOS",TO_CHAR(HIRE_DATE,'YYYY') AS "AÑO",  DEPARTMENT_ID FROM EMPLOYEES GROUP BY TO_CHAR(HIRE_DATE,'YYYY'), DEPARTMENT_ID; 

SELECT COUNT(*) AS "NUMERO DE EMPLEADOS",DEPARTMENT_ID FROM EMPLOYEES WHERE MANAGER_ID IS NOT NULL AND DEPARTMENT_ID IS NOT NULL GROUP BY DEPARTMENT_ID HAVING COUNT(*)>5;


