/*************1. Joins-Natural-Using-On**************/
SELECT COUNTRY_NAME, REGION_NAME FROM COUNTRIES NATURAL JOIN REGIONS; 

SELECT CITY,COUNTRY_NAME, REGION_NAME FROM LOCATIONS NATURAL JOIN COUNTRIES NATURAL JOIN REGIONS; 

SELECT ROUND(AVG(SALARY),2),DEPARTMENT_NAME FROM EMPLOYEES JOIN DEPARTMENTS USING(DEPARTMENT_ID) GROUP BY DEPARTMENT_NAME;

SELECT DEPARTMENT_NAME, FIRST_NAME, CITY FROM DEPARTMENTS d JOIN EMPLOYEES e ON d.manager_id=e.employee_id join LOCATIONS using(LOCATION_ID);

SELECT JOB_TITLE, DEPARTMENT_NAME, LAST_NAME, HIRE_DATE FROM EMPLOYEES  join DEPARTMENTS  USING(DEPARTMENT_ID) join JOBS using(JOB_ID) WHERE HIRE_DATE BETWEEN '01/01/2000' AND '31/12/2004' ;

SELECT JOB_TITLE, AVG(SALARY) FROM EMPLOYEES JOIN JOBS USING(JOB_ID) GROUP BY JOB_TITLE;

SELECT COUNT(*),REGION_NAME FROM DEPARTMENTS JOIN LOCATIONS USING(LOCATION_ID) JOIN COUNTRIES USING(COUNTRY_ID) JOIN REGIONS USING(REGION_ID) GROUP BY REGION_NAME;

SELECT FIRST_NAME, DEPARTMENT_NAME, COUNTRY_NAME FROM EMPLOYEES JOIN DEPARTMENTS USING (DEPARTMENT_ID) JOIN LOCATIONS USING(LOCATION_ID) JOIN COUNTRIES USING(COUNTRY_ID) ORDER BY FIRST_NAME ASC;