SELECT DEPARTMENT_NAME, MANAGER_ID,LOCATION_ID, 
CASE DEPARTMENT_ID
    WHEN 90 THEN 'Direccion'
    WHEN 50 THEN 'TRANSPORTE'
    ELSE 'OTRO DEPARTAMENTO' END AS "DEPARTMENT ID"
FROM DEPARTMENTS;

SELECT CITY, CASE 
    WHEN COUNTRY_ID IN('US','CA') THEN 'NORTMEAMERICA'
    WHEN COUNTRY_ID IN('CH', 'UK', 'DE', 'IT') THEN 'EUROPA'
    WHEN COUNTRY_ID = 'BR' THEN 'AMERICA DEL SUR'
    ELSE 'OTRA ZONA' END AS "CONTINENTE"
FROM LOCATIONS;

SELECT DEPARTMENT_NAME, MANAGER_ID,LOCATION_ID, 
DECODE(DEPARTMENT_ID,
         90, 'Direccion',
         50, 'TRANSPORTE',
         'OTRO DEPARTAMENTO') AS "DEPARTMENT ID"
FROM DEPARTMENTS;
