CREATE TABLE PRODUCTOS
(
 CODIGO NUMBER NOT NULL primary key
, NOMBRE VARCHAR2(100) NOT NULL
, PRECIO NUMBER NOT NULL
, UNIDADES NUMBER
, FECHA_ALTA DATE
);

INSERT INTO PRODUCTOS (CODIGO, NOMBRE, PRECIO, UNIDADES, FECHA_ALTA)
VALUES ('1','Tornillo','100',10,'01-09-2017');

INSERT INTO PRODUCTOS 
VALUES ('2','Tuercas','50',5,'01-10-2009');

INSERT INTO PRODUCTOS (CODIGO, NOMBRE, PRECIO)
VALUES ('3','Martillo','90');

--no funciona porque el precio es not null
INSERT INTO PRODUCTOS (CODIGO,NOMBRE,unidades)
VALUES (4,'Arandela',10);
--solucion
INSERT INTO PRODUCTOS (CODIGO,NOMBRE,precio,unidades)
VALUES (4,'Arandela',0,10);


--creando segunda tabla
CREATE TABLE PRODUCTOS2
(CODE NUMBER primary key,
NAME VARCHAR2(100));

INSERT INTO PRODUCTOS2 
SELECT CODIGO, NOMBRE FROM PRODUCTOS WHERE UNIDADES > 8;

UPDATE PRODUCTOS
SET NOMBRE=UPPER(NOMBRE)
WHERE PRECIO>50;

UPDATE PRODUCTOS
SET PRECIO=PRECIO+5
WHERE LOWER(NOMBRE) LIKE 't%';

DELETE FROM PRODUCTOS
WHERE UNIDADES < 10 OR UNIDADES IS NULL;

TRUNCATE TABLE PRODUCTOS2  ;
SELECT * FROM PRODUCTOS2;