SELECT FIRST_NAME , PHONE_NUMBER FROM EMPLOYEES;

SELECT FIRST_NAME AS "NOMBRE", JOB_ID AS "Tipo de Trabajo" FROM EMPLOYEES;

SELECT * FROM REGIONS;

SELECT COUNTRY_NAME AS "nombres de los países" FROM COUNTRIES;

SELECT STREET_ADDRESS AS "dirección", CITY AS "Ciudad", STATE_PROVINCE AS "Estado" FROM LOCATIONS;