SELECT FIRST_NAME, SALARY AS "Bruto", (SALARY*.2) AS "Impuestos", (SALARY*.8) AS "Neto" FROM EMPLOYEES;

SELECT FIRST_NAME AS "Nombre", SALARY AS "Salario", (SALARY * 14) AS "Salario anual" FROM EMPLOYEES;
