/**********FUNCIONES CARACTER*********/
SELECT * FROM LOCATIONS WHERE LENGTH(STREET_ADDRESS)>=15 AND COUNTRY_ID IN ('CA','US');

SELECT FIRST_NAME, LENGTH(FIRST_NAME) AS "LONGITUD DEL NOMBRE", LAST_NAME, SALARY*14 AS "SALARIO ANUAL" FROM EMPLOYEES WHERE  SUBSTR(LAST_NAME,4) like '%b%';

SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 4000 AND 7000 AND INSTR(LOWER(FIRST_NAME),'a')<>0 AND COMMISSION_PCT is not null;

SELECT FIRST_NAME, LAST_NAME,CONCAT(SUBSTR(FIRST_NAME, 1, 1), CONCAT('.',CONCAT(SUBSTR(LAST_NAME,1,1),'.'))) AS "INICIALES" FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE SUBSTR(FIRST_NAME,1,1)='S' OR SUBSTR(LAST_NAME,1,1)='S';

SELECT FIRST_NAME, SALARY,RPAD('*',FLOOR(SALARY/1000), '*') AS "ESTRELLAS" FROM EMPLOYEES ORDER BY SALARY DESC;

/*********FUNCIONES NUMERICAS********/
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY FROM EMPLOYEES WHERE MOD(EMPLOYEE_ID,2)<>0;

SELECT TRUNC(25.67,0), ROUND(25.67,0) FROM DUAL;

SELECT TRUNC(25.67,1), ROUND(25.67,1) FROM DUAL;

SELECT TRUNC(25.34,1), ROUND(25.34,1) FROM DUAL;

SELECT TRUNC(25.34,2), ROUND(25.34,2) FROM DUAL;

SELECT TRUNC(25.67,-1), ROUND(25.67,-1) FROM DUAL;

/*********FUNCIONES DE FECHA********/
SELECT FIRST_NAME, HIRE_DATE, TRUNC(SYSDATE-HIRE_DATE,0) AS "DIAS TRABAJADOS" FROM EMPLOYEES;

SELECT SYSDATE+15 AS "FECHA DENTRO DE 15 DIAS" FROM DUAL;

SELECT ROUND(MONTHS_BETWEEN(TO_DATE('24/12/2023','DD/MM/YYYY'),SYSDATE),1) AS "MESES HASTA NAVIDAD" FROM DUAL;

SELECT HIRE_DATE, LAST_DAY(HIRE_DATE) AS "ULTIMO DIA DEL MES" FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE ROUND(LAST_DAY(HIRE_DATE)-HIRE_DATE)<=15;

