/****************WHERE***************/

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = '100';

SELECT CITY AS "ciudad", STREET_ADDRESS AS "dirección" FROM LOCATIONS WHERE COUNTRY_ID = 'US';

SELECT * FROM COUNTRIES WHERE REGION_ID = '3';

SELECT FIRST_NAME AS "nombre", SALARY AS "salario", MANAGER_ID FROM EMPLOYEES where not MANAGER_ID = '114';

SELECT * FROM EMPLOYEES WHERE HIRE_DATE > '31/12/05';

SELECT * FROM EMPLOYEES WHERE JOB_ID = 'ST_CLERK';

SELECT * FROM EMPLOYEES WHERE LAST_NAME = 'Smith';

/*********** BETWEEN and IN************/

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID BETWEEN 40 AND 60; 

SELECT * FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '01/01/2002' and '31/12/2004';

SELECT * FROM EMPLOYEES WHERE FIRST_NAME BETWEEN 'D%' AND 'G%';

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN ('30','60','90');

SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('IT_PROG','PU_CLERK');

SELECT * FROM LOCATIONS WHERE COUNTRY_ID IN ('UK','JP');

/*********** LIKE ************/

SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE 'J%';

SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE 'S%n';

SELECT * FROM countries WHERE country_name LIKE '_r%';

/*********** NULL ************/

SELECT * FROM LOCATIONS WHERE STATE_PROVINCE IS NULL;

SELECT FIRST_NAME AS "Nombre", SALARY AS "Salario", COMMISSION_PCT AS "Comision", SALARY + COMMISSION_PCT  AS "Sueldo total" FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL; 

/*********** AND OR NOT ************/

SELECT FIRST_NAME AS "nombre", HIRE_DATE AS "fecha dee entrada", JOB_ID AS "tipo de empleado", SALARY FROM EMPLOYEES WHERE JOB_ID='IT_PROG' AND SALARY<'6000';

SELECT * FROM EMPLOYEES WHERE department_id IN (50,80) AND FIRST_NAME LIKE 'S%' AND SALARY>'3000';

SELECT * FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG' AND HIRE_DATE LIKE '%/%/07';
